### ISSUE TITLE
.entry-content pre の font-size が重複している

### ISSUE THREAD

**Issue by munierujp** [hatena/Hatena-Blog-Theme-Boilerplate#9]
`_core.scss`ファイルにおいて、`.entry-content pre`内に`font-size`が2回登場し、重複しています。

```scss
    pre {
        background: $bg-light;
        border: none;
        white-space: pre-wrap;
        text-overflow: ellipsis;
        font-size: 100%;
        line-height: 1.3;
        font-size: .8rem;
        padding: 10px;
        & > code {
            margin: 0;
            padding: 0;
            white-space: pre;
            border: none;
            background-color: transparent;
            font-family: 'Monaco', 'Consolas', 'Courier New', Courier, monospace, sans-serif;
        }
    }
```
